---
- name: install maven
  hosts: all
  gather_facts: true
  become: yes

  vars_files:
    - zeus-vars-olympus/account.yml
    - zeus-vars-olympus/olympus.yml

  roles:
    - podman

  pre_tasks:

    - set_fact:
        user_home: "/home/{{ username }}"

    - name: Register
      redhat_subscription:
        state: present
        username: "{{ credential_username }}"
        password: "{{ credential_password }}"
        autosubscribe: yes

    - name: Update yum
      yum:
        name: "*"
        state: latest

    - include_role:
        name: account
      vars:
        account:
          username: "{{ username }}"
          uid: "{{ user_uid }}"
          group: "{{ group }}"
          gid: "{{ user_gid }}"
          password: "{{ password }}"
          home: "{{ user_home }}"
